export const EMITTER_TYPE = {
  FILTER_CUSTOMER: 'customer:filter',
  CREATE_CUSTOMER: 'customer:create',
  GMAP_CHANGE: 'gmap:change',
  GMAP_CHANGE_EDIT: 'gmap:change:edit',
  GMAP_CLICK: 'gmap:click',
  CREATE_SALE_ACTIVITY: 'saleActivity:create',
  FILTER_SALE_ACTIVITY: 'saleActivity:filter',
  REMOVE_SALE_ACTIVITY: 'saleActivity:remove',
  UPDATE_SALE_ACTIVITY: 'saleActivity:update',
  FILTER_POLICY: 'policy:filter',
  CREATE_POLICY: 'policy:create',
  CREATE_BTS: 'bts:create',
  FILTER_BTS: 'bts:filter',
  GMAP_DISTANCE: 'gmap:distance',
  GMAP_BTS: 'gmap:bts',
  GMAP_BTS_CREATE: 'gmap:bts:create',
  FILTER_CARE_ACTIVITY: 'careActivity:filter',
  CREATE_CARE_ACTIVITY: 'careActivity:create',
  CREATE_QUOTATION: 'quotation:create',
  CHANGE_CUSTOMER_QUOTATION: 'quotation:changeCustomer',
  FILTER_QUOTATION: 'quotation:filter',
  FILTER_PROPOSAL: 'proposal:filter',
  FILTER_DASHBOARD: 'dashboard:filter',
  CREATE_USER: 'user:create',
  CREATE_SALE_ACTIVITY_2: 'saleActivity2:create',
  FILTER_SALE_ACTIVITY_2: 'saleActivity2:filter',
};
